version: '3'
services:
  auth-service:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
    networks:
      - shared

  money-service:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - ./money-service:/usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
    networks:
      - shared

  share-service:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - ./share-service:/usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
    networks:
      - shared

networks:
  shared:
